const CONFIG_URL='/ra-preview/chatbot/api/runtime.json',TOKEN_KEY='somun-ops-session-v1';
const $=selector=>document.querySelector(selector),statusNames={queued:'확인 대기',received:'접수 확인',consulting:'상담 중',completed:'상담 완료'},nextStatus={queued:'received',received:'consulting',consulting:'completed'};
let config=null,sessionToken=sessionStorage.getItem(TOKEN_KEY)||'',me=null,leads=[],partners=[];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadConfig(){config=await fetch(CONFIG_URL,{cache:'no-store'}).then(r=>r.json());if(!config.configured)throw new Error('운영 API가 아직 연결되지 않았습니다.');}
async function api(path,{method='GET',body,raw=false}={}){if(!config)await loadConfig();const response=await fetch(config.apiBase.replace(/\/$/,'')+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(sessionToken?{authorization:'Bearer '+sessionToken}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!response.ok){const value=await response.json().catch(()=>({}));throw new Error(value.error||'요청을 처리하지 못했습니다.');}return raw?response:response.json();}
function setLoggedIn(value){$('#login').hidden=value;$('#desk').hidden=!value;$('#logout').hidden=!value;}
function assignmentControl(lead){if(me?.role!=='admin'||!partners.length)return'';const options=partners.map(partner=>`<option value="${esc(partner.id)}" ${partner.id===lead.partnerId?'selected':''}>${esc(partner.name)}</option>`).join('');return`<label class="assign">담당 총판<select data-assignment-select>${options}</select><button data-assign="${esc(lead.id)}">배정 변경</button></label>`;}
function render(){const counts=Object.fromEntries(Object.keys(statusNames).map(key=>[key,leads.filter(v=>v.status===key).length]));$('#summary').innerHTML=Object.entries(statusNames).map(([key,label])=>`<div><strong>${counts[key]}</strong><span>${label}</span></div>`).join('');$('#leads').innerHTML=leads.length?leads.map(lead=>`<article class="lead"><div><strong>${esc(lead.name)}</strong><small>${esc(lead.id)}</small></div><div><a href="tel:${esc(lead.phone)}">${esc(lead.phone)}</a><small>${new Date(lead.createdAt).toLocaleString('ko-KR')}</small></div><div>${esc(lead.address)}<small>${lead.selectedProducts.map(esc).join(' · ')||'선택 상품 없음'}</small></div><div><span class="state">${statusNames[lead.status]}</span><small>파기 ${new Date(lead.expiresAt).toLocaleDateString('ko-KR')}</small></div><div class="actions">${nextStatus[lead.status]?`<button data-next="${nextStatus[lead.status]}" data-id="${esc(lead.id)}">${statusNames[nextStatus[lead.status]]}</button>`:''}<button data-events="${esc(lead.id)}">이력</button></div>${assignmentControl(lead)}</article>`).join(''):'<p>현재 조건의 접수가 없습니다.</p>';}
async function refresh(){try{$('#status').textContent='최신 접수를 확인하고 있습니다.';const query=$('#filter').value?'?status='+encodeURIComponent($('#filter').value):'';leads=(await api('/api/ops/leads'+query)).leads;render();$('#status').textContent=`${new Date().toLocaleTimeString('ko-KR')} 기준 · ${leads.length}건`;}catch(error){$('#status').textContent=error.message;}}
async function boot(){try{await loadConfig();if(!sessionToken)return;me=await api('/api/ops/me');setLoggedIn(true);$('#identity').textContent=me.role==='admin'?'브로씨앤씨 관리자':'제휴 총판 전용';await refresh();if(me.role==='admin')await loadAdmin();}catch{sessionStorage.removeItem(TOKEN_KEY);sessionToken='';setLoggedIn(false);}}
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,submit=form.querySelector('button');submit.disabled=true;$('#login-error').textContent='';try{const values=Object.fromEntries(new FormData(form));const result=await api('/api/ops/login',{method:'POST',body:values});sessionToken=result.token;sessionStorage.setItem(TOKEN_KEY,sessionToken);me={role:result.role};$('#identity').textContent=result.businessName+' · '+(result.role==='admin'?'관리자':'제휴 총판');setLoggedIn(true);form.reset();await refresh();if(result.role==='admin')await loadAdmin();}catch(error){$('#login-error').textContent=error.message;}finally{submit.disabled=false;}});
$('#logout').onclick=()=>{sessionStorage.removeItem(TOKEN_KEY);sessionToken='';me=null;setLoggedIn(false);$('#identity').textContent='로그인 전';};$('#refresh').onclick=refresh;$('#filter').onchange=refresh;
$('#leads').onclick=async event=>{const next=event.target.dataset.next,id=event.target.dataset.id,eventsId=event.target.dataset.events,assignId=event.target.dataset.assign;try{if(next){event.target.disabled=true;await api('/api/ops/leads/'+encodeURIComponent(id),{method:'PATCH',body:{status:next}});await refresh();}if(assignId){const partnerId=event.target.closest('.assign').querySelector('[data-assignment-select]').value;event.target.disabled=true;await api('/api/ops/leads/'+encodeURIComponent(assignId),{method:'PATCH',body:{partnerId}});await refresh();$('#status').textContent='담당 총판을 변경하고 처리 이력에 기록했습니다.';}if(eventsId){const data=await api('/api/ops/leads/'+encodeURIComponent(eventsId)+'/events');$('#events').innerHTML=data.events.map(item=>`<article><strong>${esc(item.event_type)}</strong><p>${esc(item.from_status||'')} ${item.to_status?'→ '+esc(item.to_status):''}</p><small>${new Date(item.created_at).toLocaleString('ko-KR')}</small></article>`).join('');$('#events-dialog').showModal();}}catch(error){event.target.disabled=false;$('#status').textContent=error.message;}};
$('#close-events').onclick=()=>$('#events-dialog').close();
$('#export').onclick=async()=>{try{const response=await api('/api/ops/export.csv',{raw:true}),blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='somun-leads-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(url);$('#status').textContent='CSV 내역을 내려받았으며 감사 이력에 기록했습니다.';}catch(error){$('#status').textContent=error.message;}};
async function loadAdmin(){$('#admin').hidden=false;const [partnerData,quality]=await Promise.all([api('/api/ops/partners'),api('/api/ops/quality')]);partners=partnerData.partners;$('#partner').innerHTML=partners.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('#quality').innerHTML=quality.rows.length?quality.rows.slice(0,20).map(row=>`<p>${esc(row.day)} · ${esc(row.intent)} · ${esc(row.outcome)} <strong>${row.count}</strong></p>`).join(''):'<p>수집된 익명 통계가 없습니다.</p>';render();}
$('#issue-key').onclick=async()=>{try{const result=await api('/api/admin/partners/'+encodeURIComponent($('#partner').value)+'/access-key',{method:'POST',body:{}}),box=$('#issued-key');box.hidden=false;box.textContent=`${result.businessName}\n${result.accessKey}\n\n이 키는 다시 표시되지 않습니다.`;}catch(error){$('#issued-key').hidden=false;$('#issued-key').textContent=error.message;}};
boot();
