import {canTransition,cleanLead,cleanSelection,operationalIssues,PURPOSE,retentionDeadline,safeQualityEvent} from './core.mjs';

const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const id=(prefix='')=>prefix+crypto.randomUUID();
const bytesToBase64=bytes=>btoa(String.fromCharCode(...bytes));
const base64ToBytes=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
const randomToken=(bytes=32)=>bytesToBase64(crypto.getRandomValues(new Uint8Array(bytes))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function sha(value){return bytesToBase64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))));}
async function tokenHash(env,value){return sha(`${env.TOKEN_PEPPER||''}:${value}`);}
async function piiKey(env){const raw=base64ToBytes(env.DATA_ENCRYPTION_KEY||'');if(raw.byteLength!==32)throw new Error('ENCRYPTION_NOT_READY');return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
async function encryptPii(env,value){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await piiKey(env),plain=new TextEncoder().encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return {ciphertext:bytesToBase64(new Uint8Array(cipher)),iv:bytesToBase64(iv)};}
async function decryptPii(env,row){const key=await piiKey(env),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(row.pii_iv)},key,base64ToBytes(row.pii_ciphertext));return JSON.parse(new TextDecoder().decode(plain));}
async function body(request){const type=request.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('JSON_REQUIRED');const value=await request.json();if(JSON.stringify(value).length>20000)throw new Error('BODY_TOO_LARGE');return value;}
function bearer(request){const value=request.headers.get('authorization')||'';return value.startsWith('Bearer ')?value.slice(7):'';}
function allowedOrigin(request,env){const origin=request.headers.get('origin');const list=String(env.ALLOWED_ORIGINS||'').split(',').map(v=>v.trim()).filter(Boolean);return origin&&list.includes(origin)?origin:null;}
function cors(request,env,response){const origin=allowedOrigin(request,env);if(!origin)return response;const headers=new Headers(response.headers);headers.set('access-control-allow-origin',origin);headers.set('vary','Origin');headers.set('access-control-allow-headers','authorization,content-type');headers.set('access-control-allow-methods','GET,POST,PATCH,DELETE,OPTIONS');return new Response(response.body,{status:response.status,headers});}
async function partners(env){return (await env.DB.prepare("SELECT id,business_name AS name,purpose,retention_days AS retentionDays,registry_version AS registryVersion FROM partners WHERE active=1 AND effective_from<=? AND (effective_until IS NULL OR effective_until>?) ORDER BY business_name").bind(now(),now()).all()).results;}
async function operatingState(env){const active=await partners(env),registryVersion=active[0]?.registryVersion||'';const issues=operationalIssues({enabled:env.OPERATIONS_ENABLED==='true',privacyContact:env.PRIVACY_CONTACT||'',partners:active,registryVersion,encryptionKey:env.DATA_ENCRYPTION_KEY||''});return {active,registryVersion,issues};}
function notice(env,state){const days=Number(env.RETENTION_DAYS)||90;return {version:env.POLICY_VERSION,partnerRegistryVersion:state.registryVersion,controller:'브로씨앤씨',purpose:'렌탈 상담 연락 및 설치 장소 확인',requiredItems:['이름','연락처','설치 주소'],retention:`상담 접수일로부터 ${days}일`,refusal:'동의를 거부할 수 있습니다. 필수 항목에 동의하지 않으면 상담 연락을 신청할 수 없습니다. 상품 탐색은 계속 이용할 수 있습니다.',privacyContact:env.PRIVACY_CONTACT,relationship:'third_party',useRestriction:'신청한 렌탈 상담과 접수 처리에만 이용합니다. 별도 동의 없는 광고 발송, 다른 상품 영업, DB 판매·재제공에는 이용하지 않습니다.',partners:state.active.map(p=>({name:p.name,purpose:p.purpose,retention:`제공받은 날부터 ${p.retentionDays}일`})),recipient:'제휴총판',transfer:{recipient:'제휴총판',purpose:PURPOSE,items:['이름','연락처','설치 주소'],retention:`제공받은 날부터 ${days}일`,refusal:'제공에 동의하지 않으면 총판 상담을 신청할 수 없습니다. 상품 탐색은 계속 이용할 수 있습니다.'}};}
async function requireCustomer(request,env,leadId){const token=bearer(request);if(!token)throw new Error('SESSION_REQUIRED');const row=await env.DB.prepare('SELECT lead_id,expires_at FROM customer_sessions WHERE token_hash=?').bind(await tokenHash(env,token)).first();if(!row||row.expires_at<=now()||leadId&&row.lead_id!==leadId)throw new Error('SESSION_REQUIRED');return row;}
async function requireOps(request,env){const token=bearer(request);if(!token)throw new Error('OPS_AUTH_REQUIRED');const session=await env.DB.prepare('SELECT token_hash,access_key_id,partner_id,role,expires_at FROM ops_sessions WHERE token_hash=?').bind(await tokenHash(env,token)).first();if(!session||session.expires_at<=now())throw new Error('OPS_AUTH_REQUIRED');return session;}
async function rateLimit(request,env,scope,limit){const ip=request.headers.get('cf-connecting-ip')||'local',day=now().slice(0,10),bucket=await sha(`${env.RATE_LIMIT_SALT||env.TOKEN_PEPPER||''}:${scope}:${ip}:${day}`),expiry=retentionDeadline(day+'T00:00:00Z',1);const current=await env.DB.prepare('SELECT count FROM rate_limits WHERE bucket=?').bind(bucket).first();if((current?.count||0)>=limit)throw new Error('RATE_LIMITED');await env.DB.prepare('INSERT INTO rate_limits(bucket,count,expires_at) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1').bind(bucket,expiry).run();}
async function receipt(env,leadId){const row=await env.DB.prepare('SELECT id,status,assigned_partner_id,created_at,updated_at,expires_at FROM leads WHERE id=?').bind(leadId).first();if(!row)throw new Error('NOT_FOUND');return {id:row.id,status:'stored',delivery:row.status,createdAt:row.created_at,updatedAt:row.updated_at,expiresAt:row.expires_at};}
async function choosePartner(env){return env.DB.prepare("SELECT p.id,p.business_name FROM partners p LEFT JOIN leads l ON l.assigned_partner_id=p.id AND l.status!='completed' WHERE p.active=1 AND p.effective_from<=? AND (p.effective_until IS NULL OR p.effective_until>?) GROUP BY p.id ORDER BY COUNT(l.id),p.business_name LIMIT 1").bind(now(),now()).first();}
async function createLead(request,env){await rateLimit(request,env,'intake',20);const state=await operatingState(env);if(state.issues.length)return json({error:'SERVICE_NOT_READY',issues:state.issues},503);const value=await body(request),lead=cleanLead(value.fields),consent=value.consent||{};if(consent.collectionUse!==true||consent.thirdParty!==true||consent.over14!==true)throw new Error('CONSENT_REQUIRED');if(consent.policyVersion!==env.POLICY_VERSION)throw new Error('POLICY_VERSION_CHANGED');if(consent.partnerRegistryVersion!==state.registryVersion)throw new Error('PARTNER_REGISTRY_CHANGED');const partner=await choosePartner(env);if(!partner)throw new Error('NO_PARTNER');const created=now(),leadId=id('lead_'),session=randomToken(),sessionExpiry=retentionDeadline(created,1/48),expires=retentionDeadline(created,Number(env.RETENTION_DAYS)||90),encrypted=await encryptPii(env,lead),selected=cleanSelection(value.selectedProducts),unresolved=cleanSelection(value.unresolved,20),recipients=state.active.map(p=>p.name);await env.DB.batch([
 env.DB.prepare('INSERT INTO leads(id,pii_ciphertext,pii_iv,pii_key_version,selected_products_json,unresolved_json,source_url,status,assigned_partner_id,created_at,updated_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(leadId,encrypted.ciphertext,encrypted.iv,env.DATA_KEY_VERSION||'v1',JSON.stringify(selected),JSON.stringify(unresolved),String(value.sourceUrl||'').slice(0,500),'queued',partner.id,created,created,expires),
 env.DB.prepare('INSERT INTO consent_events(id,lead_id,policy_version,registry_version,recipients_json,collection_use,third_party,over_14,agreed_at) VALUES(?,?,?,?,?,1,1,1,?)').bind(id('consent_'),leadId,env.POLICY_VERSION,state.registryVersion,JSON.stringify(recipients),created),
 env.DB.prepare('INSERT INTO customer_sessions(token_hash,lead_id,expires_at,created_at) VALUES(?,?,?,?)').bind(await tokenHash(env,session),leadId,sessionExpiry,created),
 env.DB.prepare('INSERT INTO lead_events(id,lead_id,actor_type,event_type,to_status,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('event_'),leadId,'customer','created','queued',JSON.stringify({partnerId:partner.id}),created)
]);return json({receipt:await receipt(env,leadId),sessionToken:session},201);}
async function customerRoute(request,env,url){if(url.pathname==='/api/session'&&request.method==='GET'){const session=await requireCustomer(request,env);return json({receipt:await receipt(env,session.lead_id)});}if(url.pathname==='/api/session'&&request.method==='DELETE'){const token=bearer(request);if(token)await env.DB.prepare('DELETE FROM customer_sessions WHERE token_hash=?').bind(await tokenHash(env,token)).run();return json({status:'ended'});}if(url.pathname==='/api/session/cancel'&&request.method==='POST')return json({status:'cancelled'});if(url.pathname==='/api/intakes'&&request.method==='POST')return createLead(request,env);
 const match=url.pathname.match(/^\/api\/intakes\/([^/]+)(?:\/(recovery-code))?$/);if(!match)return null;const leadId=match[1];await requireCustomer(request,env,leadId);if(request.method==='GET'&&!match[2])return json(await receipt(env,leadId));if(request.method==='DELETE'&&!match[2]){const found=await env.DB.prepare('SELECT id FROM leads WHERE id=?').bind(leadId).first();if(found)await env.DB.batch([env.DB.prepare('DELETE FROM leads WHERE id=?').bind(leadId),env.DB.prepare('INSERT INTO lead_events(id,lead_id,actor_type,event_type,metadata_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('event_'),leadId,'customer','deleted','{}',now())]);return json({status:'deleted',deletionConfirmed:!!found});}if(request.method==='POST'&&match[2]){const secret=randomToken(18),expires=(await env.DB.prepare('SELECT expires_at FROM leads WHERE id=?').bind(leadId).first())?.expires_at;if(!expires)throw new Error('NOT_FOUND');await env.DB.prepare('INSERT INTO recovery_codes(lead_id,code_hash,expires_at,created_at) VALUES(?,?,?,?) ON CONFLICT(lead_id) DO UPDATE SET code_hash=excluded.code_hash,expires_at=excluded.expires_at,created_at=excluded.created_at').bind(leadId,await tokenHash(env,secret),expires,now()).run();return json({code:leadId+'.'+secret,expiresAt:expires});}return null;}
async function recover(request,env){await rateLimit(request,env,'recover',30);const value=await body(request),full=String(value.code||''),split=full.indexOf('.'),leadId=split>0?full.slice(0,split):'',secret=split>0?full.slice(split+1):'';const row=await env.DB.prepare('SELECT lead_id,expires_at FROM recovery_codes WHERE lead_id=? AND code_hash=?').bind(leadId,await tokenHash(env,secret)).first();if(!row||row.expires_at<=now())throw new Error('INVALID_RECOVERY_CODE');const token=randomToken(),expires=retentionDeadline(now(),1/48);await env.DB.batch([env.DB.prepare('DELETE FROM customer_sessions WHERE lead_id=?').bind(row.lead_id),env.DB.prepare('INSERT INTO customer_sessions(token_hash,lead_id,expires_at,created_at) VALUES(?,?,?,?)').bind(await tokenHash(env,token),row.lead_id,expires,now())]);return json({receipt:await receipt(env,row.lead_id),sessionToken:token});}
async function opsLogin(request,env){await rateLimit(request,env,'ops-login',30);const value=await body(request),businessName=String(value.businessName||'').trim(),accessKey=String(value.accessKey||'');let key;if(businessName==='브로씨앤씨'&&env.OPS_ADMIN_TOKEN&&accessKey===env.OPS_ADMIN_TOKEN){key={id:'env-admin',partner_id:null,role:'admin'};}else{key=await env.DB.prepare('SELECT k.id,k.partner_id,k.role FROM ops_access_keys k JOIN partners p ON p.id=k.partner_id WHERE p.business_name=? AND k.key_hash=? AND k.active=1 AND p.active=1').bind(businessName,await tokenHash(env,accessKey)).first();}if(!key)throw new Error('OPS_AUTH_FAILED');const token=randomToken(),created=now(),expires=retentionDeadline(created,1/3);if(key.id==='env-admin'){await env.DB.prepare("INSERT OR IGNORE INTO ops_access_keys(id,partner_id,role,key_hash,label,active,created_at) VALUES('env-admin',NULL,'admin','env-admin','환경 관리자',1,?)").bind(created).run();}await env.DB.batch([env.DB.prepare('INSERT INTO ops_sessions(token_hash,access_key_id,partner_id,role,expires_at,created_at) VALUES(?,?,?,?,?,?)').bind(await tokenHash(env,token),key.id,key.partner_id,key.role,expires,created),env.DB.prepare('UPDATE ops_access_keys SET last_used_at=? WHERE id=?').bind(created,key.id)]);return json({token,role:key.role,expiresAt:expires,businessName});}
function leadWhere(session){return session.role==='admin'?['1=1',[]]:['assigned_partner_id=?',[session.partner_id]];}
async function listLeads(request,env,url,session){const [where,binds]=leadWhere(session),status=url.searchParams.get('status'),values=[...binds];let clause=where;if(status&&['queued','received','consulting','completed'].includes(status)){clause+=' AND status=?';values.push(status);}const result=await env.DB.prepare(`SELECT id,pii_ciphertext,pii_iv,status,assigned_partner_id,selected_products_json,unresolved_json,created_at,updated_at,expires_at FROM leads WHERE ${clause} ORDER BY created_at DESC LIMIT 100`).bind(...values).all();const leads=[];for(const row of result.results){const pii=await decryptPii(env,row);leads.push({id:row.id,...pii,status:row.status,partnerId:row.assigned_partner_id,selectedProducts:JSON.parse(row.selected_products_json),unresolved:JSON.parse(row.unresolved_json),createdAt:row.created_at,updatedAt:row.updated_at,expiresAt:row.expires_at});}return json({leads});}
async function exportLeads(env,session){const [where,binds]=leadWhere(session),result=await env.DB.prepare(`SELECT id,pii_ciphertext,pii_iv,status,selected_products_json,created_at,expires_at FROM leads WHERE ${where} ORDER BY created_at DESC LIMIT 100`).bind(...binds).all(),lines=[['접수번호','이름','연락처','설치주소','상태','선택상품','접수시각','파기예정']];for(const row of result.results){const pii=await decryptPii(env,row);lines.push([row.id,pii.name,pii.phone,pii.address,row.status,JSON.parse(row.selected_products_json).join(' | '),row.created_at,row.expires_at]);}const quote=value=>'"'+String(value??'').replaceAll('"','""')+'"',csv='\ufeff'+lines.map(row=>row.map(quote).join(',')).join('\r\n'),created=now();if(result.results.length)await env.DB.batch(result.results.map(row=>env.DB.prepare('INSERT INTO lead_events(id,lead_id,actor_type,actor_ref,event_type,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('event_'),row.id,session.role,session.access_key_id,'exported','{}',created)));return new Response(csv,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="somun-leads-${created.slice(0,10)}.csv"`,'cache-control':'no-store'}});}
async function opsRoute(request,env,url){if(url.pathname==='/api/ops/login'&&request.method==='POST')return opsLogin(request,env);const session=await requireOps(request,env);if(url.pathname==='/api/ops/me'&&request.method==='GET')return json({role:session.role,partnerId:session.partner_id});if(url.pathname==='/api/ops/leads'&&request.method==='GET')return listLeads(request,env,url,session);if(url.pathname==='/api/ops/export.csv'&&request.method==='GET')return exportLeads(env,session);if(url.pathname==='/api/ops/partners'&&request.method==='GET'){if(session.role!=='admin')throw new Error('FORBIDDEN');return json({partners:await partners(env)});}if(url.pathname==='/api/ops/quality'&&request.method==='GET'){if(session.role!=='admin')throw new Error('FORBIDDEN');const rows=(await env.DB.prepare("SELECT substr(created_at,1,10) day,outcome,intent,feedback_reason feedbackReason,COUNT(*) count FROM quality_events WHERE created_at>=datetime('now','-30 days') GROUP BY day,outcome,intent,feedback_reason ORDER BY day DESC").all()).results;return json({rows});}
 const match=url.pathname.match(/^\/api\/ops\/leads\/([^/]+)(?:\/(events))?$/);if(!match)return null;const leadId=match[1],lead=await env.DB.prepare('SELECT id,status,assigned_partner_id FROM leads WHERE id=?').bind(leadId).first();if(!lead||session.role!=='admin'&&lead.assigned_partner_id!==session.partner_id)throw new Error('NOT_FOUND');if(request.method==='GET'&&match[2])return json({events:(await env.DB.prepare('SELECT actor_type,event_type,from_status,to_status,metadata_json,created_at FROM lead_events WHERE lead_id=? ORDER BY created_at DESC LIMIT 100').bind(leadId).all()).results});if(request.method==='PATCH'&&!match[2]){const value=await body(request),next=value.status?String(value.status):lead.status,nextPartner=value.partnerId?String(value.partnerId):lead.assigned_partner_id;if(value.partnerId&&session.role!=='admin')throw new Error('FORBIDDEN');if(next!==lead.status&&!canTransition(lead.status,next,session.role))throw new Error('INVALID_TRANSITION');if(next===lead.status&&nextPartner===lead.assigned_partner_id)throw new Error('NO_CHANGE');if(nextPartner!==lead.assigned_partner_id&&!await env.DB.prepare('SELECT id FROM partners WHERE id=? AND active=1').bind(nextPartner).first())throw new Error('INVALID_PARTNER');const changed=now(),eventType=nextPartner!==lead.assigned_partner_id?'assigned':'status_changed';await env.DB.batch([env.DB.prepare('UPDATE leads SET status=?,assigned_partner_id=?,updated_at=? WHERE id=?').bind(next,nextPartner,changed,leadId),env.DB.prepare('INSERT INTO lead_events(id,lead_id,actor_type,actor_ref,event_type,from_status,to_status,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id('event_'),leadId,session.role,session.access_key_id,eventType,lead.status,next,JSON.stringify({fromPartnerId:lead.assigned_partner_id,toPartnerId:nextPartner}),changed)]);return json({receipt:await receipt(env,leadId)});}return null;}
async function provisionKey(request,env,url){const session=await requireOps(request,env);if(session.role!=='admin')throw new Error('FORBIDDEN');const match=url.pathname.match(/^\/api\/admin\/partners\/([^/]+)\/access-key$/);if(!match||request.method!=='POST')return null;const partner=await env.DB.prepare('SELECT id,business_name FROM partners WHERE id=? AND active=1').bind(match[1]).first();if(!partner)throw new Error('NOT_FOUND');const accessKey=randomToken(24),created=now();await env.DB.prepare('INSERT INTO ops_access_keys(id,partner_id,role,key_hash,label,active,created_at) VALUES(?,?,?,?,?,1,?)').bind(id('key_'),partner.id,'partner',await tokenHash(env,accessKey),partner.business_name,created).run();return json({businessName:partner.business_name,accessKey,issuedAt:created},201);}
async function quality(request,env){await rateLimit(request,env,'quality',500);const event=safeQualityEvent(await body(request)),created=now();await env.DB.prepare('INSERT INTO quality_events(id,outcome,intent,selected_count,feedback_reason,created_at) VALUES(?,?,?,?,?,?)').bind(id('quality_'),event.outcome,event.intent,event.selectedCount,event.feedbackReason,created).run();return json({accepted:true},202);}
async function cleanup(env){const cutoff=now();const expired=(await env.DB.prepare('SELECT id FROM leads WHERE expires_at<=? LIMIT 500').bind(cutoff).all()).results;for(const lead of expired){await env.DB.batch([env.DB.prepare('DELETE FROM leads WHERE id=?').bind(lead.id),env.DB.prepare('INSERT INTO lead_events(id,lead_id,actor_type,event_type,metadata_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('event_'),lead.id,'system','retention_deleted','{}',cutoff)]);}await env.DB.batch([env.DB.prepare('DELETE FROM customer_sessions WHERE expires_at<=?').bind(cutoff),env.DB.prepare('DELETE FROM ops_sessions WHERE expires_at<=?').bind(cutoff),env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<=?').bind(cutoff)]);return expired.length;}
function errorResponse(error){const code=error?.message||'INTERNAL_ERROR',client=new Set(['INVALID_FIELDS','UNCONSENTED_FIELD','INVALID_NAME','INVALID_PHONE','INVALID_ADDRESS','CONSENT_REQUIRED','POLICY_VERSION_CHANGED','PARTNER_REGISTRY_CHANGED','INVALID_RECOVERY_CODE','INVALID_EVENT','UNSAFE_EVENT','INVALID_TRANSITION','INVALID_PARTNER','NO_CHANGE','JSON_REQUIRED','BODY_TOO_LARGE']);const auth=new Set(['SESSION_REQUIRED','OPS_AUTH_REQUIRED','OPS_AUTH_FAILED']);const missing=new Set(['NOT_FOUND','NO_PARTNER']);const status=code==='RATE_LIMITED'?429:auth.has(code)?401:code==='FORBIDDEN'?403:missing.has(code)?404:client.has(code)?400:500;return json({error:status===500?'INTERNAL_ERROR':code},status);}
async function route(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204});if(url.pathname==='/api/status'&&request.method==='GET'){const state=await operatingState(env);return json({available:state.issues.length===0,mode:state.issues.length?'setup':'operational',missing:state.issues,notice:notice(env,state)});}if(url.pathname==='/api/recover'&&request.method==='POST')return recover(request,env);if(url.pathname==='/api/quality'&&request.method==='POST')return quality(request,env);if(url.pathname.startsWith('/api/admin/'))return (await provisionKey(request,env,url))||json({error:'NOT_FOUND'},404);if(url.pathname.startsWith('/api/ops/'))return (await opsRoute(request,env,url))||json({error:'NOT_FOUND'},404);return (await customerRoute(request,env,url))||json({error:'NOT_FOUND'},404);}
export default {async fetch(request,env){try{const origin=request.headers.get('origin');if(origin&&!allowedOrigin(request,env))return json({error:'ORIGIN_NOT_ALLOWED'},403);return cors(request,env,await route(request,env));}catch(error){return cors(request,env,errorResponse(error));}},async scheduled(_event,env,ctx){ctx.waitUntil(cleanup(env));}};
export {cleanup,route};
